trigger:
 - master

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: component
    type: object
    default:
     - resourcegroup
     - storageaccount
steps:
- ${{ each value in parameters.component }}
  - script: echo ${{ value }}