trigger:
 - master

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: component
    type: object
    default:
     - resourcegroup
     - storageaccount
steps:
- ${{ each filename in parameters.component }}
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure-test1'
    backendAzureRmResourceGroupName: 'terraform-rg'
    backendAzureRmStorageAccountName: 'aviaccount'
    backendAzureRmContainerName: 'avicontainer'
    backendAzureRmKey: 'test.tfstate'