trigger:
 - master

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: components
    type: object
    default:
     - resourcegroup
     - storageaccount
     
steps:
 - ${{ each filename in parameters.components }}:
   - task: TerraformInstaller@0
     inputs:
       terraformVersion: '0.13.7'