trigger:
 - master

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: components
    type: object
    default:
     - resourcegroup
     - storageaccount
     
steps:
 - ${{ each value in parameters.components }}:
   - task: TerraformInstaller@0
     displayName: Install
     inputs:
       terraformVersion: '0.13.7'
   - task: TerraformTaskV2@2
     displayName: INIT for ${{ value }}
     inputs:
       provider: 'azurerm'
       command: 'init'
       workingDirectory: '$(System.DefaultWorkingDirectory)/${{ value }}'
       backendServiceArm: 'azure-test1'
       backendAzureRmResourceGroupName: 'terraform-rg'
       backendAzureRmStorageAccountName: 'aviaccount'
       backendAzureRmContainerName: 'avicontainer'
       backendAzureRmKey: 'terraform.tfstate'
   
 